KEYS = [
    "const",
    "var",
    "def",
    "del",
    "return",
    "while",
    "for",
    "if",
    "break",
    "continue",
    "class",
    "unsafe",
]  # Добавили break и continue

DATA_TYPES = [
    "bool",
    "int",
    "float",
    "float16",
    "float32",
    "float64",
    "int8",
    "int16",
    "int32",
    "int64",
    "int8_t",
    "int16_t",
    "int32_t",
    "int64_t",
    "uint8",
    "uint16",
    "uint32",
    "uint64",
    "uint8_t",
    "uint16_t",
    "uint32_t",
    "uint64_t",
    "str",
    "None",
    "pointer",
    "list",
    "dict",
    "set",
    "tuple",
    "list[int]",
    "list[float]",
    "list[str]",
    "list[bool]",
    "list[tuple]",
    "tuple[int]",
    "tuple[float]",
    "tuple[str]",
    "tuple[bool]",
    "dict[str]",
    "dict[int]",
    "dict[float]",
    "set[int]",
    "set[str]",
    "set[float]",
    "*int",
    "*float",
    "*str",
    "*bool",
    "*tuple",  # указатели
]

METHOD_DECORATORS = ["@staticmethod", "@classmethod"]

KNOWN_C_TYPES = set(
    [
        "int",
        "float",
        "double",
        "char",
        "bool",
        "void",
        "size_t",
        "ssize_t",
        "FILE",
        "pthread_t",
        "pthread_mutex_t",
        "pthread_cond_t",
        "time_t",
        "clock_t",
        "ocean_tensor_handle_t",
        "ocean_file_handle_t",
        "ocean_json_handle_t",
        "ocean_os_dir_list_t",
        "ocean_socket_handle_t",
        "ocean_http_response_t",
        "ocean_web_app_t",
        "ocean_web_router_t",
        "ocean_web_request_t",
        "ocean_web_response_t",
        "ocean_web_handler_t",
    ]
)

DEFAULT_C_IMPORTS = [
    "#include <stdio.h>",
    "#include <stdlib.h>",
    "#include <string.h>",
    "#include <stdbool.h>",
]

INITIAL_LIST_CAPACITY = 4
