#define _POSIX_C_SOURCE 200809L
#include "web_runtime.h"
#include <arpa/inet.h>
#include <ctype.h>
#include <errno.h>
#include <netdb.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <strings.h>
#include <sys/socket.h>
#include <unistd.h>
#ifndef MSG_NOSIGNAL
#define MSG_NOSIGNAL 0
#endif
#define MAX_HEADER (64*1024)
#define DEFAULT_MAX_BODY (10*1024*1024)
typedef struct {char *method; char *pattern; ocean_web_handler_t handler;} route_t;
typedef struct header_node {char *name; char *value; struct header_node *next;} header_node;
struct ocean_web_app {route_t *routes; size_t count,cap; char *server; int max_body;};
struct ocean_web_request {char *method,*path,*query,*body,*headers,*remote; const char *pattern;};
struct ocean_web_response {int status; char *ctype,*body; header_node *headers;};
typedef struct {char *data; size_t size,cap;} buf_t;
static void die(const char *op,const char *msg){fprintf(stderr,"Ocean web error: %s: %s\n",op,msg?msg:"error");exit(1);} 
static void *xm(size_t n){void *p=malloc(n);if(!p)die("malloc","oom");return p;} static void *xr(void*p,size_t n){void*q=realloc(p,n);if(!q)die("realloc","oom");return q;}
static char *xs(const char*s){if(!s)s="";size_t n=strlen(s);char*p=xm(n+1);memcpy(p,s,n+1);return p;} static char *xsn(const char*s,size_t n){char*p=xm(n+1);memcpy(p,s,n);p[n]=0;return p;}
static void bi(buf_t*b){b->cap=4096;b->size=0;b->data=xm(b->cap);b->data[0]=0;} static void ba(buf_t*b,const void*p,size_t n){if(!n)return;size_t need=b->size+n+1;if(need>b->cap){while(b->cap<need)b->cap*=2;b->data=xr(b->data,b->cap);}memcpy(b->data+b->size,p,n);b->size+=n;b->data[b->size]=0;} static void bc(buf_t*b,const char*s){if(s)ba(b,s,strlen(s));}
static const char *reason(int s){switch(s){case 200:return"OK";case 201:return"Created";case 202:return"Accepted";case 204:return"No Content";case 301:return"Moved Permanently";case 302:return"Found";case 307:return"Temporary Redirect";case 308:return"Permanent Redirect";case 400:return"Bad Request";case 401:return"Unauthorized";case 403:return"Forbidden";case 404:return"Not Found";case 405:return"Method Not Allowed";case 409:return"Conflict";case 413:return"Payload Too Large";case 415:return"Unsupported Media Type";case 422:return"Unprocessable Entity";case 429:return"Too Many Requests";case 500:return"Internal Server Error";case 503:return"Service Unavailable";default:return"Status";}}
static int listen_fd(const char*host,int port){char ps[16];snprintf(ps,sizeof(ps),"%d",port);struct addrinfo h={0},*l=NULL;h.ai_family=AF_UNSPEC;h.ai_socktype=SOCK_STREAM;h.ai_flags=AI_PASSIVE;int rc=getaddrinfo((host&&*host)?host:NULL,ps,&h,&l);if(rc)die("getaddrinfo",gai_strerror(rc));for(struct addrinfo*i=l;i;i=i->ai_next){int fd=socket(i->ai_family,i->ai_socktype,i->ai_protocol);if(fd<0)continue;int yes=1;(void)setsockopt(fd,SOL_SOCKET,SO_REUSEADDR,&yes,sizeof(yes));if(bind(fd,i->ai_addr,i->ai_addrlen)==0&&listen(fd,256)==0){freeaddrinfo(l);return fd;}close(fd);}freeaddrinfo(l);die("serve",strerror(errno));return -1;}
static void sendall(int fd,const char*d,size_t n){size_t o=0;while(o<n){ssize_t s=send(fd,d+o,n-o,MSG_NOSIGNAL);if(s<0&&errno==EINTR)continue;if(s<=0)return;o+=(size_t)s;}}
static bool nextseg(const char **c,const char **s,size_t *n){const char*p=*c;while(*p=='/')p++;if(!*p){*c=p;return false;}const char*b=p;while(*p&&*p!='/')p++;*s=b;*n=(size_t)(p-b);*c=p;return true;} static bool paramseg(const char*s,size_t n){return n>=3&&s[0]=='{'&&s[n-1]=='}';}
static bool matchpath(const char*pat,const char*path){if(!strcmp(pat,"/")&&!strcmp(path,"/"))return true;const char*a=pat,*b=path;for(;;){const char*as,*bs;size_t an,bn;bool ah=nextseg(&a,&as,&an),bh=nextseg(&b,&bs,&bn);if(!ah||!bh)return ah==bh;if(paramseg(as,an))continue;if(an!=bn||strncmp(as,bs,an))return false;}}
static char *decode(const char*v,size_t n){char*out=xm(n+1);size_t w=0;for(size_t i=0;i<n;i++){if(v[i]=='%'&&i+2<n&&isxdigit((unsigned char)v[i+1])&&isxdigit((unsigned char)v[i+2])){char h[3]={v[i+1],v[i+2],0};out[w++]=(char)strtol(h,NULL,16);i+=2;}else if(v[i]=='+')out[w++]=' ';else out[w++]=v[i];}out[w]=0;return out;}
static char *hval(const char*h,const char*n,const char*d){if(!h)return xs(d);size_t nl=strlen(n);const char*c=h;while(*c){const char*e=strstr(c,"\r\n");if(!e)e=c+strlen(c);const char*col=memchr(c,':',(size_t)(e-c));if(col&&(size_t)(col-c)==nl&&!strncasecmp(c,n,nl)){const char*v=col+1;while(v<e&&(*v==' '||*v=='\t'))v++;return xsn(v,(size_t)(e-v));}if(!*e)break;c=e+2;}return xs(d);} static long clen(const char*h){char*v=hval(h,"Content-Length","0"),*e=NULL;long n=strtol(v,&e,10);bool ok=e!=v&&*e==0&&n>=0;free(v);return ok?n:-1;}
static char *pairval(const char*q,const char*n,const char*d){if(!q)return xs(d);size_t nl=strlen(n);const char*c=q;while(*c){const char*e=strchr(c,'&');if(!e)e=c+strlen(c);const char*eq=memchr(c,'=',(size_t)(e-c));const char*k=eq?eq:e;if((size_t)(k-c)==nl&&!strncmp(c,n,nl))return eq?decode(eq+1,(size_t)(e-eq-1)):xs("");if(!*e)break;c=e+1;}return xs(d);}
static char *remote_copy(const struct sockaddr_storage*a,socklen_t l){char h[128],s[32];if(getnameinfo((const struct sockaddr*)a,l,h,sizeof(h),s,sizeof(s),NI_NUMERICHOST|NI_NUMERICSERV))return xs("");size_t z=strlen(h)+strlen(s)+4;char*out=xm(z);snprintf(out,z,a->ss_family==AF_INET6?"[%s]:%s":"%s:%s",h,s);return out;}
static ocean_web_request_t readreq(int fd,const struct sockaddr_storage*r,socklen_t rl,int max,int*err){*err=0;buf_t b;bi(&b);char chunk[4096],*hend=NULL;while(!hend){ssize_t n=recv(fd,chunk,sizeof(chunk),0);if(n<0&&errno==EINTR)continue;if(n<=0){free(b.data);*err=400;return NULL;}ba(&b,chunk,(size_t)n);if(b.size>MAX_HEADER){free(b.data);*err=413;return NULL;}hend=strstr(b.data,"\r\n\r\n");}size_t hb=(size_t)(hend-b.data)+4;char*le=strstr(b.data,"\r\n");if(!le){free(b.data);*err=400;return NULL;}char*line=xsn(b.data,(size_t)(le-b.data));char*s1=strchr(line,' '),*s2=s1?strchr(s1+1,' '):NULL;if(!s1||!s2){free(line);free(b.data);*err=400;return NULL;}*s1=0;*s2=0;char*m=xs(line),*target=xs(s1+1);free(line);char*h=xsn(le+2,(size_t)(hend-(le+2)));long bl=clen(h);if(bl<0||bl>max){free(m);free(target);free(h);free(b.data);*err=bl>max?413:400;return NULL;}size_t have=b.size-hb;while(have<(size_t)bl){ssize_t n=recv(fd,chunk,sizeof(chunk),0);if(n<0&&errno==EINTR)continue;if(n<=0){free(m);free(target);free(h);free(b.data);*err=400;return NULL;}ba(&b,chunk,(size_t)n);have+=(size_t)n;}char*body=xsn(b.data+hb,(size_t)bl);free(b.data);char*qmark=strchr(target,'?');char*path=qmark?xsn(target,(size_t)(qmark-target)):xs(target);char*q=qmark?xs(qmark+1):xs("");free(target);ocean_web_request_t req=xm(sizeof(*req));req->method=m;req->path=path;req->query=q;req->body=body;req->headers=h;req->remote=remote_copy(r,rl);req->pattern=NULL;return req;}
static void freereq(ocean_web_request_t r){if(!r)return;free(r->method);free(r->path);free(r->query);free(r->body);free(r->headers);free(r->remote);free(r);} 
char *ocean_web_request_method_copy(ocean_web_request_t r){return xs(r?r->method:"");} char *ocean_web_request_path_copy(ocean_web_request_t r){return xs(r?r->path:"");} char *ocean_web_request_query_copy(ocean_web_request_t r){return xs(r?r->query:"");} char *ocean_web_request_body_copy(ocean_web_request_t r){return xs(r?r->body:"");} char *ocean_web_request_remote_copy(ocean_web_request_t r){return xs(r?r->remote:"");} char *ocean_web_request_header_copy(ocean_web_request_t r,const char*n,const char*d){return r?hval(r->headers,n,d):xs(d);} char *ocean_web_request_query_param_copy(ocean_web_request_t r,const char*n,const char*d){return r?pairval(r->query,n,d):xs(d);} 
char *ocean_web_request_path_param_copy(ocean_web_request_t r,const char*n,const char*d){if(!r||!r->pattern)return xs(d);const char*a=r->pattern,*b=r->path;size_t nl=strlen(n);for(;;){const char*as,*bs;size_t an,bn;bool ah=nextseg(&a,&as,&an),bh=nextseg(&b,&bs,&bn);if(!ah||!bh)break;if(paramseg(as,an)&&an-2==nl&&!strncmp(as+1,n,nl))return decode(bs,bn);}return xs(d);}
static ocean_web_response_t mkres(int s,const char*c,const char*b){ocean_web_response_t r=xm(sizeof(*r));r->status=s;r->ctype=xs(c);r->body=xs(b);r->headers=NULL;return r;} ocean_web_response_t ocean_web_response_text(int s,const char*b){return mkres(s,"text/plain; charset=utf-8",b);} ocean_web_response_t ocean_web_response_json(int s,const char*b){return mkres(s,"application/json; charset=utf-8",b);} ocean_web_response_t ocean_web_response_html(int s,const char*b){return mkres(s,"text/html; charset=utf-8",b);} ocean_web_response_t ocean_web_response_empty(int s){return mkres(s,"","");} ocean_web_response_t ocean_web_response_redirect(int s,const char*l){ocean_web_response_t r=mkres(s,"text/plain; charset=utf-8","");ocean_web_response_add_header(r,"Location",l);return r;}
void ocean_web_response_add_header(ocean_web_response_t r,const char*n,const char*v){if(!r||!n)return;header_node*h=xm(sizeof(*h));h->name=xs(n);h->value=xs(v);h->next=r->headers;r->headers=h;} void ocean_web_response_release(ocean_web_response_t r){if(!r)return;header_node*h=r->headers;while(h){header_node*n=h->next;free(h->name);free(h->value);free(h);h=n;}free(r->ctype);free(r->body);free(r);} static bool hasrh(ocean_web_response_t r,const char*n){for(header_node*h=r->headers;h;h=h->next)if(!strcasecmp(h->name,n))return true;return false;}
static void writeres(int fd,ocean_web_app_t app,ocean_web_response_t r,bool head){bool owned=false;if(!r){r=ocean_web_response_text(500,"handler returned null response");owned=true;}buf_t b;bi(&b);char line[128];snprintf(line,sizeof(line),"HTTP/1.1 %d %s\r\n",r->status,reason(r->status));bc(&b,line);if(app->server&&*app->server&&!hasrh(r,"Server")){bc(&b,"Server: ");bc(&b,app->server);bc(&b,"\r\n");}if(r->ctype&&*r->ctype&&!hasrh(r,"Content-Type")){bc(&b,"Content-Type: ");bc(&b,r->ctype);bc(&b,"\r\n");}for(header_node*h=r->headers;h;h=h->next){bc(&b,h->name);bc(&b,": ");bc(&b,h->value);bc(&b,"\r\n");}size_t n=strlen(r->body?r->body:"");if(!hasrh(r,"Content-Length")){char lh[64];snprintf(lh,sizeof(lh),"Content-Length: %zu\r\n",n);bc(&b,lh);}if(!hasrh(r,"Connection"))bc(&b,"Connection: close\r\n");bc(&b,"\r\n");if(!head)ba(&b,r->body,n);sendall(fd,b.data,b.size);free(b.data);if(owned)ocean_web_response_release(r);}
ocean_web_app_t ocean_web_app_create(void){ocean_web_app_t a=xm(sizeof(*a));a->routes=NULL;a->count=a->cap=0;a->server=xs("Ocean");a->max_body=DEFAULT_MAX_BODY;return a;} void ocean_web_app_release(ocean_web_app_t a){if(!a)return;for(size_t i=0;i<a->count;i++){free(a->routes[i].method);free(a->routes[i].pattern);}free(a->routes);free(a->server);free(a);} 
void ocean_web_route(ocean_web_app_t a,const char*m,const char*p,ocean_web_handler_t h){if(!a||!m||!p||p[0]!='/'||!h)die("route","invalid route");if(a->count==a->cap){a->cap=a->cap?a->cap*2:16;a->routes=xr(a->routes,a->cap*sizeof(*a->routes));}a->routes[a->count++]=(route_t){xs(m),xs(p),h};}
#define R(fn,m) void fn(ocean_web_app_t a,const char*p,ocean_web_handler_t h){ocean_web_route(a,m,p,h);} 
R(ocean_web_get,"GET") R(ocean_web_post,"POST") R(ocean_web_put,"PUT") R(ocean_web_patch,"PATCH") R(ocean_web_delete,"DELETE") R(ocean_web_options,"OPTIONS") R(ocean_web_head,"HEAD") R(ocean_web_any,"*")
#undef R
void ocean_web_set_server_header(ocean_web_app_t a,const char*v){if(!a)return;free(a->server);a->server=xs(v);} void ocean_web_set_max_body_bytes(ocean_web_app_t a,int v){if(!a||v<=0)die("max_body","invalid value");a->max_body=v;}
static route_t *findroute(ocean_web_app_t a,ocean_web_request_t r,bool*pex){*pex=false;route_t*head=NULL;for(size_t i=0;i<a->count;i++){route_t*x=&a->routes[i];if(!matchpath(x->pattern,r->path))continue;*pex=true;if(!strcmp(x->method,r->method)||!strcmp(x->method,"*"))return x;if(!strcmp(r->method,"HEAD")&&!strcmp(x->method,"GET"))head=x;}return head;}
static void errres(int fd,ocean_web_app_t a,int s){ocean_web_response_t r=ocean_web_response_text(s,reason(s));writeres(fd,a,r,false);ocean_web_response_release(r);} 
void ocean_web_serve(ocean_web_app_t a,const char*host,int port){if(!a)die("serve","null app");int sfd=listen_fd(host,port);printf("Ocean web server listening on http://%s:%d\n",(host&&*host)?host:"0.0.0.0",port);fflush(stdout);for(;;){struct sockaddr_storage remote;socklen_t rl=sizeof(remote);int cfd;do{cfd=accept(sfd,(struct sockaddr*)&remote,&rl);}while(cfd<0&&errno==EINTR);if(cfd<0)continue;int es=0;ocean_web_request_t req=readreq(cfd,&remote,rl,a->max_body,&es);if(!req){errres(cfd,a,es?es:400);close(cfd);continue;}bool pe=false;route_t*rt=findroute(a,req,&pe);if(!rt){errres(cfd,a,pe?405:404);freereq(req);close(cfd);continue;}req->pattern=rt->pattern;ocean_Request *request_object=ocean_create_Request(req);ocean_Response *response_object=rt->handler(request_object);ocean_web_response_t resp=response_object?ocean_Response_take_handle(response_object):NULL;writeres(cfd,a,resp,!strcmp(req->method,"HEAD"));if(resp)ocean_web_response_release(resp);free(response_object);free(request_object);freereq(req);close(cfd);}}
